services:
  backend:
    container_name: backend
    hostname: backend
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - "19999:8000"
    env_file:
      - .env
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    networks:
      - main_network

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend/app:/app
    ports:
      - "20000:8001"
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8001
    networks:
      - main_network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sportshop
      POSTGRES_PASSWORD: sportshop123
      POSTGRES_DB: sportshop
    ports:
      - "5432:5432"
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

